Test shard functionalties
gluster/glusto-tests pull request #68
Opened 2021-05-12 06:51 UTC by v-harihar

2021-05-12 07:09 UTC, kshithijiyer requested changes
I see alot of pylint issues in your code that's why it seems to be failing on the build system, could you please fix them?

2021-05-12 08:31 UTC, v-harihar commented
@kshithijiyer sure will check. Meanwhile, Can you please provide your review comments? I will address both in the next patch

2021-05-13 05:19 UTC, kshithijiyer requested changes
I have a few comments to reduce the number of lines. Have s look at them and let me know what you feel about them.

2021-05-13 05:19 UTC, kshithijiyer commented on tests/functional/shard/test_shard_functionalties.py
> +                         "volume option - features.shard-deletion-rate: 100")
You can try using a loop here instead:
```   
       # verify sharding xlator is enabled
        for val, exp_val, err_msg in (('features.shard', 'on', 'features.shard: on'),
                                                       ('features.shard-block-size', '64MB', "features.shard-block-size: 64Mb")):
            self.assertEqual(vol_option_dict[val], exp_val, "Failed"         
                                        " to validate volume option - {}".format(err_msg)) 
```

2021-05-13 05:19 UTC, kshithijiyer commented on tests/functional/shard/test_shard_functionalties.py
> +        self.assertEqual(vol_option_dict['features.shard-deletion-rate'], '200', "Failed"
Same as above

2021-05-13 05:19 UTC, kshithijiyer commented on tests/functional/shard/test_shard_functionalties.py
> +        self.assertEqual(vol_option_dict['features.shard-deletion-rate'], '100', "Failed"
Same as above

2021-06-14 05:54 UTC, balakreddy commented
@v-harihar There are a lot of unused imports in the file, you can find the pylint job here: https://build.gluster.org/job/gh_glusto-tests-lint/57/console. Please resend the patch with changes.

Thanks

2021-09-28 10:10 UTC, closed without merging